### ISSUE TITLE
Create a dynamic block to replace the [bw_csv] shortcode

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-block#24]
The [bw_csv] shortcode, delivered in oik-bob-bing-wide, provides a variety of formatting options for content entered as Comma Separated Values. 
Since Gutenberg doesn’t yet support an ASIS block, which could be used as one solution to the problem, we should develop a dynamic block that supports the functionality implemented for the bw_csv shortcode 

### Proposed solution

**Comment by bobbingwide** [comment]
At @WordCampLondon last weekend, I considered the best way of implementing the `uo=table|u|ul|o|ol|d|dl` parameter to the shortcode, which is used to switch the display of the content. 

I realised this could be achieved using the toolbar icons. 

uo value | Icon | For
-------- | ------ | -----
default, table | editor-table | Generate HTML table
u, ul |  editor-ul | Unordered list
o, ol | editor-ol | Ordered list
d, dl | ? | Description list. 

The Advanced settings area could be used for the other attributes
```
th="y| n - Format table headings"
y="| Y| N - Convert y to a dash icon tick or cross"
n="| N| Y - Convert n to a dash icon cross or tick"
del,sep=",| | - Delimeter between columns
```
It will also show the textual representation of the `uo=` attribute.

**Comment by bobbingwide** [comment]
The oik-csv block does not work with Gutenberg 4.0.0
Uncaught TypeError: withInstanceId is not a function
